### ISSUE TITLE
--no-color config?

### ISSUE THREAD

**Issue by c4ys** [jgonera/autoless#28]
I see it in lessc, how use it in autoless?
  --no-color               Disables colorized output.
@black:"#000000"
@names:black,white
@name:extact(@names,1)
well get a error
```less
// Colors
@transparent: transparent;
@black: #000000;
@white: #ffffff;
@lime: #a4c400;
@green: #60a917;
@emerald: #008a00;
@blue: #00AFF0;
@teal: #00aba9;
@cyan: #1ba1e2;
@cobalt: #0050ef;
@indigo: #6a00ff;
@violet: #aa00ff;
@pink: #dc4fad;
@magenta: #d80073;
@crimson: #a20025;
@red: #CE352C;
@orange: #fa6800;
@amber: #f0a30a;
@yellow: #e3c800;
@brown: #825a2c;
@olive: #6d8764;
@steel: #647687;
@mauve: #76608a;
@taupe: #87794e;
@dark: #1d1d1d;
@darkBrown: #63362F;
@darkCrimson: #640024;
@darkMagenta: #81003C;
@darkIndigo: #4B0096;
@darkCyan: #1B6EAE;
@darkCobalt: #00356A;
@darkTeal: #004050;
@darkEmerald: #003e00;
@darkGreen: #128023;
@darkOrange: #bf5a15;
@darkRed: #9a1616;
@darkPink: #9a165a;
@darkViolet: #57169a;
@darkBlue: #16499a;
@lightBlue: #4390df;
@lighterBlue: #00CCFF;
@lightTeal: lighten(@teal, 30%);
@lightOlive: #78aa1c;
@lightOrange: lighten(@orange, 30%);
@lightPink: #f472d0;
@lightRed: lighten(@red, 10%);
@lightGreen: lighten(@green, 10%);
@lightCyan: #59cde2;
@grayed: #585858;
@grayDarker: #222222;
@darker: #222222;
@grayDark: #333333;
@gray: #555555;
@grayLight: #999999;
@grayLighter: #eeeeee;
@darkGray: #333333;
@darkerGray: #222222;
@lightGray: #999999;
@lighterGray: #eeeeee;

@color-list: black, white, lime, green, emerald, blue, teal, cyan, cobalt, indigo, violet, pink, magenta, crimson, red, orange,
amber, yellow, brown, olive, steel, mauve, taupe, dark, darkBrown, darkCrimson, darkMagenta, darkIndigo, darkCyan,
darkCobalt, darkTeal, darkEmerald, darkGreen, darkOrange, darkRed, darkPink, darkViolet, darkBlue, lightBlue,
lighterBlue, lightTeal, lightOlive, lightOrange, lightPink, lightRed, lightGreen, lightCyan, grayed, grayDarker,
grayDark, gray, grayLight, grayLighter, lightGray, lighterGray, darkGray, darkerGray, darker;

@color-list-length: length(@color-list);

.generate-colors(@name, @i: 1) when (@i =< @color-list-length) {
  @name: extract(@color-list, @i);
  .fg-@{name} {color: @@name !important;}
  .bg-@{name} {background-color: @@name !important;}
  .generate-colors(@name, @i + 1);
}
.generate-colors(@color-list-length);
```
